#!/bin/bash

wildLength=$((40-${#1}))

if [[ $wildLength -lt 0 ]]
then
    echo matching key is too long
    exit 1
fi

regex=^$1[a-z0-9]{$wildLength}$

while read line
do
    if [[ $line =~ $regex ]]
    then
        if [[ -z $hash ]]
        then
            hash=$line
        else
            echo mulitiple matches
            exit 1
        fi
    fi
done <<END
$(git log --format=%H)
END

if [[ -n $hash ]]
then
    echo $hash
else
    echo no match
fi